
version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: crmuser
      POSTGRES_PASSWORD: crmpass
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
    command: ["npm","run","start:dev"]

  frontend:
    build: ./frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["npm","run","dev"]

volumes:
  db-data:
